version: "3"

services:
  app:
    container_name: pkhex-api
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./PKHeX.API:/app
      - /app/obj/ # <- directory won't be mounted
      - /app/bin/ # <- directory won't be mounted
    command: sh -c "dotnet watch run -v --project PKHeX.API.csproj --urls http://*:5000"
